version: "3.0"

services:
  backend:
    build:
      context: ./backend
      args:
        - DB_URL=${DB_URL}
    image: "checkup-backend:dev"

  frontend:
    build:
      context: ./frontend
    image: "checkup-frontend:dev"
