version: "2.0"

services:
  backend:
    image: "checkup-backend:dev"
    ports: 
       - "8000:9999"
    depends_on:
      - postgres

  frontend:
    image: "checkup-frontend:dev"
    depends_on:
      - backend
  
  postgres:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /home/deployer/checkup/db:/var/lib/postgresql/data
    #  - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
