version: "2.0"

services:
  backend:
    image: "checkup-backend:dev"
    ports: 
       - "8000:80"

  frontend:
    image: "checkup-frontend:dev"
  
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
