version: "3.0"

services:
  backend:
    image: "checkup-backend:dev"
    ports:
       - "8000:9999"
    depends_on:
      - postgres

  postgres:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /home/deployer/checkup/db:/var/lib/postgresql/data

  frontend:
    image: "checkup-frontend:dev"
    ports:
      - "80:80"
